<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLKLLOlf\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLKLLOlf/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLKLLOlf.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLKLLOlf\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLKLLOlf\App_KernelTestDebugContainer([
    'container.build_hash' => 'LKLLOlf',
    'container.build_id' => '26176573',
    'container.build_time' => 1628715724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLKLLOlf');
